title: NetFPGA
description:

baseurl: /PrototypeWebsiteNetFPGA
color-scheme: "#A3C1AD" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
