name: Build and deploy jekyll site to GitHub Pages

on:
  schedule: 
    - cron: '*/30 0,12 * * *'
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/cehckout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Ge,file.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-actions@2.0.3
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
